import { Product } from '@/types';

export const mockProducts: Product[] = [
  {
    id: 'mock-1',
    name: 'Jujube Honey 250gm',
    slug: 'jujube-honey-250gm',
    description: 'Pure Jujube honey harvested from pristine valleys. Rich in antioxidants and known for its distinctive taste. Please note: The flavor, color, and aroma may vary according to the season and available flowers, which is a natural characteristic of pure, raw honey.',
    price: 400,
    image_url: '/placeholder-honey.svg',
    stock: 50,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    name: 'Jujube Honey 500gm',
    slug: 'jujube-honey-500gm',
    description: 'Pure Jujube honey harvested from pristine valleys. Rich in antioxidants and known for its distinctive taste. Please note: The flavor, color, and aroma may vary according to the season and available flowers, which is a natural characteristic of pure, raw honey.',
    price: 750,
    image_url: '/placeholder-honey.svg',
    stock: 40,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    name: 'Multiflora Honey 250gm',
    slug: 'multiflora-honey-250gm',
    description: 'A delightful blend of nectars from multiple flower sources. Rich, complex flavor profile with diverse health benefits. Please note: The flavor, color, and aroma may vary according to the season and available flowers, which is a natural characteristic of pure, raw honey.',
    price: 350,
    image_url: '/placeholder-honey.svg',
    stock: 60,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    name: 'Multiflora Honey 500gm',
    slug: 'multiflora-honey-500gm',
    description: 'A delightful blend of nectars from multiple flower sources. Rich, complex flavor profile with diverse health benefits. Please note: The flavor, color, and aroma may vary according to the season and available flowers, which is a natural characteristic of pure, raw honey.',
    price: 650,
    image_url: '/placeholder-honey.svg',
    stock: 50,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-5',
    name: 'Ajwain Honey 250gm',
    slug: 'ajwain-honey-250gm',
    description: 'Unique honey with the beneficial properties of Ajwain (carom seeds). Known for digestive and medicinal benefits. Please note: The flavor, color, and aroma may vary according to the season and available flowers, which is a natural characteristic of pure, raw honey.',
    price: 450,
    image_url: '/placeholder-honey.svg',
    stock: 35,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-6',
    name: 'Ajwain Honey 500gm',
    slug: 'ajwain-honey-500gm',
    description: 'Unique honey with the beneficial properties of Ajwain (carom seeds). Known for digestive and medicinal benefits. Please note: The flavor, color, and aroma may vary according to the season and available flowers, which is a natural characteristic of pure, raw honey.',
    price: 850,
    image_url: '/placeholder-honey.svg',
    stock: 30,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
